\set ON_ERROR_STOP on

\getenv app_dbo_password POSTGRES_APP_DBO_PASSWORD
\getenv app_api_password POSTGRES_APP_API_PASSWORD
\getenv app_health_password POSTGRES_HEALTHCHECK_PASSWORD

SELECT format(
  'CREATE ROLE nevo_dbo LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
  :'app_dbo_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nevo_dbo') \gexec

SELECT format(
  'ALTER ROLE nevo_dbo WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
  :'app_dbo_password'
) \gexec

SELECT format(
  'CREATE ROLE nevo_api LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
  :'app_api_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nevo_api') \gexec

SELECT format(
  'ALTER ROLE nevo_api WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
  :'app_api_password'
) \gexec

SELECT format(
  'CREATE ROLE nevo_health LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
  :'app_health_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nevo_health') \gexec

SELECT format(
  'ALTER ROLE nevo_health WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
  :'app_health_password'
) \gexec

SELECT 'CREATE DATABASE nevo OWNER nevo_dbo ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'nevo') \gexec

REVOKE ALL ON DATABASE nevo FROM PUBLIC;
GRANT CONNECT, TEMP ON DATABASE nevo TO nevo_dbo;
GRANT CONNECT ON DATABASE nevo TO nevo_api;
GRANT CONNECT ON DATABASE nevo TO nevo_health;

\connect nevo

CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION nevo_dbo;
ALTER SCHEMA public OWNER TO nevo_dbo;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO nevo_dbo;
GRANT USAGE ON SCHEMA public TO nevo_api;

CREATE SCHEMA IF NOT EXISTS partman AUTHORIZATION nevo_dbo;
CREATE EXTENSION IF NOT EXISTS pg_partman WITH SCHEMA partman;

GRANT CREATE, USAGE ON SCHEMA public TO nevo_dbo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO nevo_api;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO nevo_api;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO nevo_api;

ALTER DEFAULT PRIVILEGES FOR ROLE nevo_dbo IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nevo_api;
ALTER DEFAULT PRIVILEGES FOR ROLE nevo_dbo IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nevo_api;
ALTER DEFAULT PRIVILEGES FOR ROLE nevo_dbo IN SCHEMA public
GRANT EXECUTE ON ROUTINES TO nevo_api;

GRANT pg_monitor TO nevo_health;

ALTER ROLE nevo_dbo IN DATABASE nevo SET search_path = public, partman;
ALTER ROLE nevo_api IN DATABASE nevo SET search_path = public;
ALTER ROLE nevo_health IN DATABASE nevo SET search_path = pg_catalog;
